---
- hosts: all
  connection: local
  gather_facts: yes
  become: false
  roles:
    - role: opsta.docker_machine
      docker_machine_create: true
      docker_machine_manage_config: true
  environment: "{{ proxy_env | default({}) }}"
