---
# Need to run one-by-one host to advoid import database problem
- hosts: all
  gather_facts: no
  become: true
  serial: 1
  roles:
    - opsta.pdns_admin
  environment: "{{ proxy_env | default({}) }}"
